jasypt:
  encryptor:
    password: milvussteve
    algorithm: PBEWITHHMACSHA512ANDAES_256
    pool-size: 1
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64

variable:
  db-class: org.mariadb.jdbc.Driver
  db-url: jdbc:mariadb://192.168.0.3:3306/test
  db-username: ENC(bIvGp1nwv93dDalDAoX3XCMGOh/E0zrjwbggFBq62zCmq/2apMU7TcPzK4UisYVE)
  db-password: ENC(bIvGp1nwv93dDalDAoX3XCMGOh/E0zrjwbggFBq62zCmq/2apMU7TcPzK4UisYVE)

